name: DevSecOps CI/CD

on:
  push:
    branches: [ main ]

jobs:
  pipeline:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Generate Semantic Version
      id: version
      uses: paulhatch/semantic-version@v5.4.0
      with:
        tag_prefix: "v"
        format: "${major}.${minor}.${patch}"
        major_pattern: "BREAKING CHANGE"
        minor_pattern: "feat"

    - name: Print version
      run: echo "VERSION=${{ steps.version.outputs.version }}"

    - name: Set Lowercase Owner
      # This step fixes the "Zee-Kay03" capital letter issue
      run: |
        echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}

    - name: Build Docker Image
      run: |
        VERSION=${{ steps.version.outputs.version }}
        # We use $REPO_OWNER (lowercase) instead of github.repository_owner
        docker build --no-cache \
          -t ghcr.io/${{ env.REPO_OWNER }}/devsecops-app:$VERSION \
          -t ghcr.io/${{ env.REPO_OWNER }}/devsecops-app:latest \
          -f app/Dockerfile app/

    - name: Scan Image with Trivy
      uses: aquasecurity/trivy-action@0.20.0
      with:
        # We use env.REPO_OWNER here too
        image-ref: ghcr.io/${{ env.REPO_OWNER }}/devsecops-app:latest
        severity: CRITICAL,HIGH
        ignore-unfixed: true
        exit-code: "0"
        timeout: "20m"

    - name: Login to GHCR
      # Login still works with the standard actor
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push Images
      run: |
        VERSION=${{ steps.version.outputs.version }}
        docker push ghcr.io/${{ env.REPO_OWNER }}/devsecops-app:$VERSION
        docker push ghcr.io/${{ env.REPO_OWNER }}/devsecops-app:latest

    - name: Create GHCR Secret in K8s
      run: |
        kubectl delete secret ghcr-secret --ignore-not-found=true
        kubectl create secret docker-registry ghcr-secret \
          --docker-server=ghcr.io \
          --docker-username=${{ github.actor }} \
          --docker-password=${{ secrets.GHCR_PAT }} \
          --docker-email=dummy@example.com

    - name: Apply Manifests
      run: kubectl apply -f k8s/

    - name: Patch Deployment With Version
      run: |
        VERSION=${{ steps.version.outputs.version }}
        # Update the deployment to use the lowercase image URL
        kubectl set image deployment/devsecops-app web=ghcr.io/${{ env.REPO_OWNER }}/devsecops-app:$VERSION

    - name: Wait for Rollout
      run: kubectl rollout status deployment/devsecops-app
